/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class a_keymaster_cryptils_Secp256k1 */

#ifndef _Included_a_keymaster_cryptils_Secp256k1
#define _Included_a_keymaster_cryptils_Secp256k1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
